config:
  domainname: vagrant.test
  iprange: "192.168"
  ansible: playbook.yml
  ansiblegroups:
    masters:
      - master1
      - master2
vms:
  master1:
    hostname: "master1"
    ip: "10.10"
    dsize: 10
  master2:
    hostname: "master2"
    ip: "10.11"
    autostart: false
  master3:
    hostname: "master3"
    ip: "10.12"
    autostart: true